### PR TITLE
utils: add permission error for getting workflows

### PR DESCRIPTION
**Pull request by DaanRosendal**
Closes reanahub/reana-server#651, closes reanahub/reana-server#650

### CODE REVIEW

**Comment by mdonadoni** [comment]
Latest version before rebase is a5726ff

Two things left:
- Fixing https://github.com/reanahub/reana-db/pull/212#pullrequestreview-1812979126 (maybe in a separate PR)
- Should we revert the last commit that adds `PermissionError`? As far as I can tell, these exceptions are never caught anywhere else in the codebase. Furthermore, the `PermissionError` exception is OS exception, so it should not be used here (see https://docs.python.org/3/library/exceptions.html#PermissionError and https://docs.python.org/3/library/exceptions.html#OSError)

**Comment by mdonadoni** [comment]
Ready to be reviewed, squashed and merged

**Comment by tiborsimko** [comment]
> Should we revert the last commit that adds `PermissionError`? 

Agreed, I'll remove it for now before merging.  (Kept local copy just in case.)

**Review by tiborsimko — APPROVED** [review]
Works nicely :+1: with

```
- r-client #692
- r-client-go #153
- r-ui #375
- r-server #658
- r-workflow-controller #552
- r-commons #429
- r-db #216
```

Removed the `PermissionError` commit and kept it locally.

**Pull request merged**
